---
title: "Genomics Aotearoa"
subtitle: "Good Practice in Scientific Computing"
author: "Mik Black"
date: "29 April 2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## GA - good practice session

Based on the papers:

 - **Good enough practices in scientific computing**:
    <BR>
    Wilson G, Bryan J, Cranston K, Kitzes J, Nederbragt L, Teal TK.  PLoS Comput Biol. 2017 Jun 22;13(6):e1005510.<BR> 
    doi: [10.1371/journal.pcbi.1005510](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510) 

 - **Ten Simple Rules for Reproducible Computational Research**
    <BR>
    Sandve GK, Nekrutenko A, Taylor J, Hovig E. PLoS Comput Biol. 2013 Oct;9(10):e1003285. 
    <BR>
    doi: [10.1371/journal.pcbi.1003285](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285)

## Overview

Sections:

 - Data Management
 - Software
 - Collaboration
 - Project Organization
 - Keeping Track of Changes
 - Manuscripts
 - Ten Rules for Reproducible Computational Research

## But first... some motivation


<p style="color:red">**1.\ Reproducibility**</p>
<p style="color:red">**2.\ Increased efficiency**</p>
<p style="color:red">**3.\ Continuity**</p>


- GA is a seven-year programme 
- Major goal is to upskill the NZ genomics research community
- Specific projects we've chosen for funding are **exemplars:** 
    - produce research outputs 
    - develop and share workflows that are relevant for the wider community

## Reproducibility + Efficiency + Continuity

 - For you:
    - recreate results (with ease)
    - reuse code and workflows
    - develop more efficient work habits
    
 - For everyone:
    - ensure reproducibility (and reduce burden)
    - establish workflows
    - enable collaboration
    - build upon existing work

## Overview

Sections:

 - Data Management
 - Software
 - Collaboration
 - Project Organization
 - Keeping Track of Changes
 - Manuscripts
 - Ten Rules for Reproducible Computational Research


## Data management

 1. Save the raw data.
    - preserve raw data - never edit
    - if needed, computationally create modified versions of raw data (e.g., data cleaning).
    
 2. Ensure raw data are backed up in more than one location
    - NeSI + host institution (i.e., "remote" storage)
    - Data sensitivity issues with cloud-based storage providers
    
 3. Create the data you wish to see in the world
    - non-proprietary formats
    - informative variable and file names
    - make it the data set you wished you had received...

## Data management
 
<ol start=4>
<li> Create analysis-friendly data

- each column is a variable
- each row is an observation
- tidy data aren't just for R...

<li> Record all the steps used to process data.

- use scripts to capture (and automate) every step of data processing and cleaning

</ol>

## Data management
 
<ol start=6>

<li> Anticipate the need to use multiple tables, and use a unique identifier for every record.

  - e.g., multiple CSV files linked by a common sample ID
  - combine data programmatically 

<li> Submit data to a reputable DOI-issuing repository so that others can access and cite it.

 - Zenodo: https://zenodo.org
 - Dryad: https://datadryad.org
 - FigShare: https://figshare.com
 
<p style="color:red">**But first: CAN you share your data?**</p>

</ol>

## Software 

 1. Place a brief explanatory comment at the start of every program.
 2. Decompose programs into functions.
 3. Be ruthless about eliminating duplication.
 4. Always search for well-maintained software libraries that do what you need.
 5. Test libraries before relying on them.
 6. Give functions and variables meaningful names.
 7. Make dependencies and requirements explicit.
 8. Do not comment and uncomment sections of code to control a program's behavior.
 9. Provide a simple example or test data set.
 10. Submit code to a reputable DOI-issuing repository.

## Collaboration 

 1. Create an overview of your project.
 2. Create a shared "to-do" list for the project.
 3. Decide on communication strategies.
 4. Make the license explicit.
 5. Make the project citable.

## Project Organisation 

 1. Put each project in its own directory, which is named after the project.
 2. Put text documents associated with the project in the doc directory.
 3. Put raw data and metadata in a data directory and files generated during cleanup and analysis in a results directory.
 4. Put project source code in the src directory.
 5. Put external scripts or compiled programs in the bin directory.
 6. Name all files to reflect their content or function.

## Keeping Track of Changes

 1. Back up (almost) everything created by a human being as soon as it is created.
 2. Keep changes small.
 3. Share changes frequently.
 4. Create, maintain, and use a checklist for saving and sharing changes to the project.
 5. Store each project in a folder that is mirrored off the researcher's working machine.
 6. Add a file called CHANGELOG.txt to the project's docs subfolder.
 7. Copy the entire project whenever a significant change has been made.
 8. Use a version control system.

## Manuscripts 

 1. Write manuscripts using online tools with rich formatting, change tracking, and reference management.
 2. Write the manuscript in a plain text format that permits version control.

## Ten Rules for Reproducible Computational Research

 - Rule 1: For Every Result, Keep Track of How It Was Produced
 - Rule 2: Avoid Manual Data Manipulation Steps
 - Rule 3: Archive the Exact Versions of All External Programs Used
 - Rule 4: Version Control All Custom Scripts
 - Rule 5: Record All Intermediate Results, When Possible in Standardized Formats
 
 
## Ten Rules for Reproducible Computational Research

 - Rule 6: For Analyses That Include Randomness, Note Underlying Random Seeds
 - Rule 7: Always Store Raw Data behind Plots
 - Rule 8: Generate Hierarchical Analysis Output, Allowing Layers of Increasing Detail to Be Inspected
 - Rule 9: Connect Textual Statements to Underlying Results
 - Rule 10: Provide Public Access to Scripts, Runs, and Results



